### ISSUE TITLE
eregi_replace Depreciation

### ISSUE THREAD

**Issue by JesterEE** [mcglow2-RPI/phpLicenseWatcher#6]
Depreciated in php 5.3 and removed in php 7.  
https://secure.php.net/manual/en/function.eregi-replace.php

Affects index.php.  A few quick changes I made manually on my install.  Not really worth the PR, but know it needs to be addressed.

**Comment by mcglow2-RPI** [comment]
Thanks for pointing this out.  While an easy fix it will affect any new users fresh install so we should get it fixed.  If you have a working version of index.php I would be happy to accept a PR on it.  If not we will add to some work we are doing.

**Comment by JesterEE** [comment]
I do have a "working" version, but "working" is a bit subjective.  It doesn't throw interpreter errors, but I did no testing on the code those cases addressed.  The implementation may still be incorrect.

Though I did create a PR mcglow2-RPI/phpLicenseWatcher#7

**Comment by mcglow2-RPI** [comment]
The deprecated function has been replaced
